### PR TITLE
Update Arch Linux instructions

### PR DESCRIPTION
**Pull request by U8NWXD**

### CODE REVIEW

**Comment by U8NWXD** [comment]
@vojtechjelinek @DubeySandeep PTAL. I know you probably can't review for correctness if you don't use Arch Linux, but please just review as best you can

**Comment by vojtechjelinek** [comment]
Actually, I can also test it since I have Arch available on one laptop. Let me know if that would be useful.

**Comment by U8NWXD** [comment]
@vojtechjelinek that would be great since the Arch Linux instructions don't get tested that often

**Review by DubeySandeep — APPROVED** [review]

**Review by seanlip — APPROVED** [review]
No particular concerns from my end, just noting that I'm not familiar with Arch Linux so my ability to give useful feedback here is limited.

**Comment by U8NWXD** [comment]
@vojtechjelinek are you still able to test these instructions? If so, that would be great

**Comment by vojtechjelinek** [comment]
@U8NWXD Sorry, I was a bit busy with other stuff I will try to look into it in the next two days.

**Review by vojtechjelinek — APPROVED** [review]
LGTM! While testing this on my Arch I managed to break my system (but not because of these instructions) so I only tested few thing at the top.

**Pull request merged**
