### PR TITLE
Add video showing how to create a new PR

### LINKED ISSUE #12: Post-Merge Questions on the "Make a Pull Request" Page
Watch for feedback from new contributors to see if the following are necessary:

* Some of the sections (like 4 + 5) are a bit long. I wonder if this will still be overwhelming. It might be worth checking with the newer onboardees once this page is published -- could ask if they had any issues getting started, have any suggestions for improvement, or check whether any of the issues appear in practice in their PRs.

* I wonder if it is worth making a short video to illustrate step 4. It might be helpful for a new contributor to see someone actually walking through the steps. (We have a youtube Oppia Developer Team channel where we can host it, if it's difficult to do so directly on GitHub.)

### PR DESCRIPTION
**Pull request by U8NWXD**
Fixes #12. Note that the video has already been shrunk and compressed

### CODE REVIEW

**Comment by U8NWXD** [comment]
@seanlip @DubeySandeep PTAL

**Review by seanlip — COMMENTED** [review]
Hm, the GIF is 45.7 MB and GitHub doesn't even load it (for me). Would a different file format (e.g. PNG, lower-res) be better, and/or would static images be better?

**Comment by U8NWXD** [comment]
@seanlip fixed. PTAL

**Review by seanlip — APPROVED** [review]
Thanks! LGTM.

Just a suggestion, there might be something to be said for adding audio narration to explain what you're doing -- makes it easier to follow along. Your call, ofc :)

**Review by DubeySandeep — APPROVED** [review]

**Pull request merged**
